[package]
name = "tests-macros"
edition = "2021"
rust-version = "1.78"
publish = false

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.55", features = ["full", "extra-traits"] }
